#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z $(which mkpasswd) ]]; then
  python -m platform | grep -qi Ubuntu && (apt-get update && apt-get install -y whois) || (yum update && yum install -y expect)
fi
